substitutions:
  _TERRAFORM_IMAGE: 'hashicorp/terraform'
  _TERRAFORM_VERSION: '0.12.26'
  _ENV: 'sandpit'
  _MODULE: ''
  _TF_LOG: ''
#options:
    #workerPool: ${_WORKER}
steps:
  - id: validate
    name: ${_TERRAFORM_IMAGE}:${_TERRAFORM_VERSION}
    entrypoint: sh
    env:
      - ENV=${_ENV}
      - MODULE=${_MODULE}
      - PROJECT_ID=${PROJECT_ID}
    args:
      - -exuo
      - pipefail
      - cloudbuild/bin/terraform-validate.sh
  - id: plan
    name: ${_TERRAFORM_IMAGE}:${_TERRAFORM_VERSION}
    entrypoint: sh
    env:
      - ENV=${_ENV}
      - MODULE=${_MODULE}
      - PROJECT_ID=${PROJECT_ID}
    args:
      - -exuo
      - pipefail
      - cloudbuild/bin/terraform-plan.sh
  - id: terratest
    name: gcr.io/cloud-builders/go
    entrypoint: sh
    env:
      - ENV=${_ENV}
      - MODULE=${_MODULE}
      - PROJECT_ID=${PROJECT_ID}
    args:
      - cloudbuild/bin/terratest-go.sh

