substitutions:
  _TERRAFORM_IMAGE: 'hashicorp/terraform'
  _TERRAFORM_VERSION: '0.12.26'
  _ENV: 'sandpit'
  _MODULE: ''
  _TF_LOG: ''
#options:
    #workerPool: ${_WORKER}
steps:
  - id: tag-release
    name: gcr.io/cloud-builders/git
    entrypoint: sh
    env:
      - ENV=${_ENV}
      - MODULE=${_MODULE}
      - PROJECT_ID=${PROJECT_ID}
      - BRANCH_NAME=${BRANCH_NAME}
    args:
      - cloudbuild/bin/git-tagging.sh
